# SPDX-License-Identifier: MPL-2.0
name: OSSF Scorecard

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  id-token: write
jobs:
  scorecard:
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@f2f8e6791b09f1f498f01b798e4670a1ebc9c986
    permissions:
      contents: read
      security-events: write
      id-token: write
